eureka:
  instance:
    hostname: eureka-server  # Name of your Eureka server container
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka  # Use container name here

name:
  value: mrsaber

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
