spring:
  application:
    name: discovery-service
  config:
    import: configserver:http://config-server:9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
