server:
  port: 8074

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stock_operation
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 0                  # disable retries
      delivery.timeout.ms: 30000  # max total time allowed to deliver a message (30 seconds)
      request.timeout.ms: 10000   # request timeout for Kafka broker (10 seconds)
      retry.backoff.ms: 1000      # wait 1 second between retries (ignored if retries=0)

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
  endpoint:
    health:
      show-details: always
